run:
  concurrency: 4
  timeout: 1m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl

linters:
  fast: true
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - dupl
    - errname
    - gci
    - gofumpt
    - ireturn